import type { NextPage } from 'next'
import Head from 'next/head'

const SuccessPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Success</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Success</p>
    </div>
  )
}

export default SuccessPage
