import type { NextPage } from 'next'
import Head from 'next/head'

const AskQuestion: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Ask your question
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">
        Ask us!
      </h1>
    </div>
  )
}

export default AskQuestion
