import type { NextPage } from 'next'
import Head from 'next/head'

const Payment: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Payment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Pay here
    </div>
  )
}

export default Payment
